language: python
sudo: required
python:
  - "3.4"

before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgraphviz-dev

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover --start-directory stl/ --pattern "*_test.py"
  - python -m unittest discover --start-directory example/ --pattern "*_test.py"
  - python sprockets_end_to_end_test.py

notification:
  email:
    - sprockets-eng@googlegroups.com
